pipeline {
    agent {
        docker {
            image 'openjdk:11'
            args '-u root' // Allow Jenkins to run Docker commands as root
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}

